name: Deploy to Cloud Run

on:
  push:
    branches:
      - main  # Or replace with your deployment branch

jobs:
  deploy:
    name: Deploy LMS App to Cloud Run
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v8

      - name: Configure Docker for Artifact Registry
        run: gcloud auth configure-docker asia-southeast1-docker.pkg.dev

      - name: Build Docker image
        run: |
          docker build -t asia-southeast1-docker.pkg.dev/sheworkslms/sheworks-repo/recyglo-lms:v6 .
          docker push asia-southeast1-docker.pkg.dev/sheworkslms/sheworks-repo/recyglo-lms:v6

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy recyglo-lms \
            --image asia-southeast1-docker.pkg.dev/sheworkslms/sheworks-repo/recyglo-lms:v6 \
            --region asia-southeast1 \
            --platform managed \
            --quiet \
            --allow-unauthenticated
